---
# tasks file for base
- name: Update apt
  apt: update_cache=no

- name : Update all packages
  apt: name="*" state=latest update_cache=true force_apt_get=true

- name: Install base packages
  apt:
    name: ["locales", "build-essential", "git", "nginx", "curl"]
    state: latest
  tags:
    - packages
